# Generated by Django 4.2.28 on 2026-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='crop_type',
            field=models.CharField(blank=True, help_text='Type of crop', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='farm_name',
            field=models.CharField(blank=True, help_text='Name of the farm (Exploitation)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='has_manager',
            field=models.BooleanField(default=False, help_text='Whether a plot manager is assigned'),
        ),
    ]
